[versions]
compottie = "1.1.0"
kotlin="1.9.21"
dokka="1.9.0"
compose="1.5.11"
androidGradlePlugin = "8.1.1"
lottie-android="6.3.0"
serialization="1.6.2"

[libraries]
lottie-android = { module ="com.airbnb.android:lottie-compose", version.ref = "lottie-android" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id ="org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
